# Generated by Django 2.1.4 on 2018-12-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_auto_20181225_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redaction',
            old_name='tag',
            new_name='tag_id',
        ),
    ]
