# Generated by Django 2.1.4 on 2018-12-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_auto_20181225_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redaction',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
