# Generated by Django 2.1.4 on 2018-12-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0005_auto_20181225_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
