# Generated by Django 2.1.4 on 2018-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0006_redaction_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaction',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
