# Generated by Django 2.1.4 on 2018-12-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0007_auto_20181227_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=120)),
                ('setting_value', models.CharField(max_length=120)),
            ],
        ),
    ]
