# Generated by Django 2.1.4 on 2018-12-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0008_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaction',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
