# Generated by Django 2.1.4 on 2019-01-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0009_auto_20181227_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=999)),
                ('page', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='redaction',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
